apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-config
  namespace: sms-dev
data:
  PORT: "5000"
  AWS_REGION: "us-east-1"
  QUEUE_URL: "http://elasticmq.sms-dev.svc.cluster.local:9324/queue/schedules"
