apiVersion: v1
kind: Secret
metadata:
  name: scheduler-secrets
  namespace: sms-dev
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "CHANGEME"
  AWS_SECRET_ACCESS_KEY: "CHANGEME"
  SOCIAL_API_TOKEN: "CHANGEME"
